[package]
name = "shared"
version = "0.1.0"
edition = "2021"

[dependencies]
ohkami = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
jsonwebtoken = { workspace = true }
bcrypt = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true }
